spring:
  application:
    name: movieinfo
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/movieinfo}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

server:
  port: 8080

movieapi:
  omdb:
    api-key: ${OMDB_API_KEY}
  tmdb:
    api-key: ${TMDB_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    hu:
      jenci:
        movieinfo: DEBUG
